import { describe, expect, test } from "bun:test";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createScanContext } from "../../src/core/create-context.ts";
import { createSupplyChainDetector } from "../../src/detectors/supply-chain/index.ts";
import { createEnvLeakDetector } from "../../src/detectors/env-leak/index.ts";
import { createInsecureCryptoDetector } from "../../src/detectors/insecure-crypto/index.ts";
import { createAiPresenceDetector } from "../../src/detectors/ai-presence/index.ts";
import { analyzeSource } from "../../src/detectors/dangerous-sinks/index.ts";
import { detectors } from "../../src/detectors/index.ts";

const FIX = join(import.meta.dir, "../fixtures");

describe("detectors registry", () => {
  test("includes all security + AI detectors", () => {
    const ids = detectors.map((d) => d.id);
    for (const id of [
      "ghost-deps",
      "secrets",
      "env-leak",
      "supply-chain",
      "dangerous-sinks",
      "insecure-crypto",
      "ai-unreviewed",
      "ai-presence",
    ]) {
      expect(ids).toContain(id);
    }
  });
});

describe("supply-chain", () => {
  test("flags postinstall curl|bash and git+http", async () => {
    const detector = createSupplyChainDetector();
    const { ctx } = createScanContext({
      rootDir: join(FIX, "supply-chain/bad-app"),
    });
    const findings = await detector.run(ctx);
    expect(findings.some((f) => f.id.includes("script:postinstall"))).toBe(true);
    expect(findings.some((f) => f.id.includes("git-http"))).toBe(true);
  });

  test("does not treat an explicit global tool install as remote execution", async () => {
    const detector = createSupplyChainDetector();
    const { ctx } = createScanContext({
      rootDir: join(FIX, "supply-chain/safe-app"),
    });
    expect(await detector.run(ctx)).toHaveLength(0);
  });
});

describe("env-leak", () => {
  test("flags an unprotected .env without duplicating secret detection", async () => {
    const detector = createEnvLeakDetector();
    const { ctx } = createScanContext({
      rootDir: join(FIX, "env-leak/bad-app"),
    });
    const findings = await detector.run(ctx);
    expect(findings.some((f) => f.id.includes("present:.env"))).toBe(true);
    expect(findings.some((f) => f.id.includes("example-secret"))).toBe(false);
  });

  test("does not penalize a local .env that is gitignored", async () => {
    const detector = createEnvLeakDetector();
    const { ctx } = createScanContext({
      rootDir: join(FIX, "env-leak/safe-app"),
    });
    expect(await detector.run(ctx)).toHaveLength(0);
  });

  test("respects negations and still flags an ignored file tracked by Git", async () => {
    const dir = await mkdtemp(join(tmpdir(), "novacheck-env-git-"));
    try {
      Bun.spawnSync(["git", "init"], { cwd: dir });
      await writeFile(
        join(dir, ".gitignore"),
        ".env*\n!.env.production\n",
      );
      await writeFile(join(dir, ".env"), "SECRET=tracked-value\n");
      await writeFile(join(dir, ".env.local"), "SECRET=ignored-value\n");
      await writeFile(
        join(dir, ".env.production"),
        "SECRET=not-ignored-value\n",
      );
      Bun.spawnSync(["git", "add", "-f", ".env"], { cwd: dir });

      const detector = createEnvLeakDetector();
      const { ctx } = createScanContext({ rootDir: dir });
      const findings = await detector.run(ctx);

      expect(findings.some((f) => f.file === ".env")).toBe(true);
      expect(
        findings.some((f) => f.file === ".env.production"),
      ).toBe(true);
      expect(findings.some((f) => f.file === ".env.local")).toBe(false);
      expect(
        findings.find((f) => f.file === ".env")?.metadata?.tracked,
      ).toBe(true);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });
});

describe("insecure-crypto", () => {
  test("flags md5, Math.random token, createCipher", async () => {
    const detector = createInsecureCryptoDetector();
    const { ctx } = createScanContext({
      rootDir: join(FIX, "insecure-crypto/bad-app"),
    });
    const findings = await detector.run(ctx);
    expect(findings.some((f) => f.id.includes("crypto-md5-sha1"))).toBe(true);
    expect(findings.some((f) => f.id.includes("crypto-math-random"))).toBe(true);
    expect(findings.some((f) => f.id.includes("crypto-create-cipher"))).toBe(
      true,
    );
  });

  test("does not flag SHA-1 used only as a file checksum", async () => {
    const detector = createInsecureCryptoDetector();
    const { ctx } = createScanContext({
      rootDir: join(FIX, "insecure-crypto/safe-app"),
    });
    expect(await detector.run(ctx)).toHaveLength(0);
  });
});

describe("ai-presence", () => {
  test("flags AI_DISCLOSURE.md and Generated by Cursor", async () => {
    const detector = createAiPresenceDetector();
    const { ctx } = createScanContext({
      rootDir: join(FIX, "ai-presence/marked-app"),
    });
    const findings = await detector.run(ctx);
    expect(findings.some((f) => f.id === "ai-presence:disclosure-md")).toBe(
      true,
    );
    expect(findings.some((f) => f.id.includes("ai-presence:file:"))).toBe(true);
  });

  test("does not treat marker regex implementations as AI provenance", async () => {
    const detector = createAiPresenceDetector();
    const { ctx } = createScanContext({
      rootDir: join(FIX, "ai-unreviewed/empty-project"),
    });
    const findings = await detector.run(ctx);
    expect(findings.some((f) => f.metadata?.source === "file-marker")).toBe(
      false,
    );
    expect(findings.some((f) => f.file?.includes("regex.ts"))).toBe(false);
    expect(findings).toHaveLength(0);
  });
});

describe("dangerous-sinks expansions", () => {
  test("flags eval and innerHTML", async () => {
    const findings = await analyzeSource(
      `
export function a(code: string, el: HTMLElement, html: string) {
  eval(code);
  el.innerHTML = html;
}
`,
      "x.ts",
      "typescript",
    );
    const kinds = new Set(findings.map((f) => f.metadata?.kind));
    expect(kinds.has("code-exec")).toBe(true);
    expect(kinds.has("xss")).toBe(true);
  });

  test("flags pickle.loads and yaml.load", async () => {
    const findings = await analyzeSource(
      `
import pickle
import yaml
def f(b, s):
    pickle.loads(b)
    yaml.load(s)
`,
      "x.py",
      "python",
    );
    expect(findings.some((f) => f.metadata?.kind === "deserialization")).toBe(
      true,
    );
  });
});
