import type { Detector, Finding, ScanContext } from "../../types/index.ts";
import { runAiPresenceScan } from "./scan.ts";

export { runAiPresenceScan } from "./scan.ts";

export function createAiPresenceDetector(): Detector {
  return {
    id: "ai-presence",
    name: "Presenza AI (marker espliciti)",
    description:
      "Rileva solo segnali espliciti: trailers git, SPDX-AI, Generated by/with, AI_DISCLOSURE.md. Nessuna guess stilistica.",
    async run(ctx: ScanContext): Promise<Finding[]> {
      const result = await runAiPresenceScan(ctx.rootDir);
      ctx.recordStats({
        detectorId: "ai-presence",
        name: "Presenza AI (marker espliciti)",
        filesReceived: result.filesReceived,
        filesAnalyzed: result.filesAnalyzed,
        discoveryPatterns: result.discoveryPatterns,
        files: result.files,
        findingsCount: result.findings.length,
      });
      return result.findings;
    },
  };
}

export const aiPresenceDetector = createAiPresenceDetector();
