import type { Detector, Finding, ScanContext } from "../../types/index.ts";
import { runAiPresenceScan } from "./scan.ts";

export { runAiPresenceScan } from "./scan.ts";

export function createAiPresenceDetector(): Detector {
  return {
    id: "ai-presence",
    name: "AI presence (explicit markers)",
    description:
      "Detects explicit signals only: Git trailers, SPDX-AI, Generated by/with, and AI_DISCLOSURE.md. No style guessing.",
    async run(ctx: ScanContext): Promise<Finding[]> {
      const result = await runAiPresenceScan(ctx.rootDir);
      ctx.recordStats({
        detectorId: "ai-presence",
        name: "AI presence (explicit markers)",
        filesReceived: result.filesReceived,
        filesAnalyzed: result.filesAnalyzed,
        discoveryPatterns: result.discoveryPatterns,
        files: result.files,
        findingsCount: result.findings.length,
      });
      return result.findings;
    },
  };
}

export const aiPresenceDetector = createAiPresenceDetector();
