import { execFile } from "node:child_process";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { promisify } from "node:util";
import type { Finding } from "../../types/index.ts";
import { listTextFiles, TEXT_FILE_DISCOVERY_PATTERNS, toRel } from "../secrets/walk.ts";

/**
 * Explicit AI-presence signals only — no style guessing.
 * Interops with commit trailers and well-known disclosure markers.
 */
export const AI_PRESENCE_PATTERNS = [
  "git log --all --format=%B (Co-Authored-By / Made-with / Generated with)",
  "source headers: SPDX-AI-Disclosure, Generated by/with Cursor|Claude|Copilot|Codex",
  "AI_DISCLOSURE.md",
] as const;

const TRAILER_RE =
  /^(?:Co-Authored-By:\s*(.+)|Made-with:\s*(Cursor|Claude|Copilot|Windsurf|Aider|Codex)|Generated with\s+(Claude Code|Cursor|GitHub Copilot)|Generated by\s+(Cursor|Claude|Copilot|ChatGPT))/gim;

const FILE_MARKER_RE =
  /^\s*(?:(?:\/\/|#|\/\*+|\*)\s*)?(?:SPDX-AI-Disclosure:\s*\S+|Generated (?:by|with)\s+(?:Cursor|Claude|Copilot|Codex|ChatGPT|Windsurf|Aider)|Co-Authored-By:\s*(?:Claude|Cursor|Copilot|GPT))/gim;

const execFileAsync = promisify(execFile);

export interface AiPresenceScanResult {
  findings: Finding[];
  filesReceived: number;
  filesAnalyzed: number;
  files: string[];
  discoveryPatterns: string[];
}

export async function runAiPresenceScan(
  rootDir: string,
): Promise<AiPresenceScanResult> {
  const findings: Finding[] = [];
  const files: string[] = [];
  let received = 0;
  let analyzed = 0;

  // AI_DISCLOSURE.md
  try {
    const abs = join(rootDir, "AI_DISCLOSURE.md");
    const raw = await readFile(abs, "utf8");
    received++;
    analyzed++;
    files.push(abs);
    findings.push({
      id: "ai-presence:disclosure-md",
      detectorId: "ai-presence",
      severity: "info",
      title: "AI_DISCLOSURE.md found",
      explanation:
        `The repository discloses AI usage through \`AI_DISCLOSURE.md\`. This supports transparency; verify that it is up to date.`,
      fixPrompt:
        `Review AI_DISCLOSURE.md and ensure it lists the tools and models actually used. This is not a security vulnerability.`,
      file: "AI_DISCLOSURE.md",
      evidence: raw.slice(0, 80).replace(/\s+/g, " "),
      metadata: { source: "ai-disclosure-md" },
    });
  } catch {
    // absent
  }

  // Git commit trailers (explicit only)
  try {
    const { stdout: out } = await execFileAsync(
      "git",
      ["-C", rootDir, "log", "-n", "50", "--format=%B---END---"],
      { encoding: "utf8", maxBuffer: 2 * 1024 * 1024 },
    );
    received++;
    analyzed++;
    const commits = out.split("---END---");
    const seen = new Set<string>();
    for (const body of commits) {
      const re = new RegExp(TRAILER_RE.source, "gim");
      let m: RegExpExecArray | null;
      while ((m = re.exec(body)) !== null) {
        const evidence = m[0].trim();
        if (seen.has(evidence)) continue;
        seen.add(evidence);
        findings.push({
          id: `ai-presence:trailer:${hash(evidence)}`,
          detectorId: "ai-presence",
          severity: "info",
          title: `AI signal in commit: ${evidence.slice(0, 60)}`,
          explanation:
            `An explicit AI-tooling trailer or marker was found in Git history. ` +
            `It indicates AI-assisted code; it does not automatically imply a bug, but the code should be reviewed before shipping.`,
          fixPrompt:
            `Ensure the AI-generated sections referenced by this marker have been reviewed by a human. ` +
            `Prefer Agent Trace or SPDX provenance for line-level traceability.`,
          evidence,
          metadata: { source: "git-trailer" },
        });
      }
    }
  } catch {
    // not a git repo / git missing
  }

  // File header markers (first 2KB)
  const textFiles = await listTextFiles(rootDir);
  received += textFiles.length;
  for (const abs of textFiles) {
    let buf: Buffer;
    try {
      buf = Buffer.from(await readFile(abs));
    } catch {
      continue;
    }
    const head = buf.subarray(0, Math.min(buf.length, 2048)).toString("utf8");
    analyzed++;
    files.push(abs);
    const re = new RegExp(FILE_MARKER_RE.source, "gim");
    const m = re.exec(head);
    if (!m) continue;
    const rel = toRel(rootDir, abs);
    const line = head.slice(0, m.index).split(/\r?\n/).length;
    findings.push({
      id: `ai-presence:file:${rel}:${hash(m[0])}`,
      detectorId: "ai-presence",
      severity: "info",
      title: `Explicit AI marker in ${rel}`,
      explanation:
        `The file explicitly discloses AI generation or assistance (\`${m[0]}\`). ` +
        `This is transparency metadata, not a vulnerability, and it does not reduce the Trust Score.`,
      fixPrompt:
        `Review ${rel} carefully for security issues, edge cases, and secrets. Update provenance if you use Agent Trace.`,
      file: rel,
      line,
      evidence: m[0].trim(),
      metadata: { source: "file-marker" },
    });
  }

  return {
    findings,
    filesReceived: received,
    filesAnalyzed: analyzed,
    files,
    discoveryPatterns: [...AI_PRESENCE_PATTERNS, ...TEXT_FILE_DISCOVERY_PATTERNS.slice(0, 2)],
  };
}

function hash(s: string): string {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return Math.abs(h).toString(36);
}
